### ISSUE TITLE
MoSh in TotalCapture preprocessing

### ISSUE THREAD

**Issue by amaliacontiero** [eth-ait/dip18#41]
Greetings and thank you for your work on Deep Inertial Poser. I've been trying to preprocess the raw TotalCapture data using your code read_TC_data.py, however, I can't comprehend what "MOSH_BASE_PATH" could be from? I have referred to any relevant MoSh datasets (official site/AMASS) but so far I haven't been able to find a lead. What data is it referring to?
Are the following lines essential to preprocessing?
[`
mosh_path = os.path.join(MOSH_BASE_PATH, name_splits[0], name_splits[1])  
mosh_gt = pkl.load(open(mosh_path))['poses']
mosh_ori_0 = pose2matrix(mosh_gt[0])
`](https://github.com/eth-ait/dip18/blob/eadd5f60db8975d499651d34268ba97b5282dccc/data_synthesis/read_TC_data.py#L161-L163)

Thank you in advance!

**Comment by amaliacontiero** [comment]
Additional information: I use the following paths,

folder_path = dip18\data_synthesis\TotalCapture_Original   (data from original TC dataset)
res_path = dip18\data_synthesis\res\  (I suppose this is the save folder)

MOSH_BASE_PATH = dip18\data_synthesis\MPI_mosh    (AMASS data as mentioned in paper, I used SMPL+H)



Traceback (most recent call last):
  File "read_TC_data.py", line 271, in <module>
    process_imu(all_imu_files[0])
  File "read_TC_data.py", line 186, in process_imu
    mosh_gt = pkl.load(open(mosh_path))['poses']
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CodeStuff\\TIP_Retrain\\dip18\\data_synthesis\\MPI_mosh\\s1\\acting1.pkl'
